### ISSUE TITLE
Nosetests fail on Shippable in Python 3.2

### ISSUE THREAD

**Issue by crempp** [crempp/mdweb#14]
See https://app.shippable.com/builds/56cc0d3dd583ab0f00fd57f6

```
Traceback (most recent call last):
  File "/home/shippable/build_ve/python/3.2/bin/nosetests", line 9, in 
    load_entry_point('nose==1.3.4', 'console_scripts', 'nosetests')()
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/usr/lib/python3.2/unittest/main.py", line 123, in __init__
    self.parseArgs(argv)
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/nose/plugins/cover.py", line 106, in configure
    import coverage
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/coverage/__init__.py", line 13, in 
    from coverage.control import Coverage, process_startup
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/coverage/control.py", line 15, in 
    from coverage.annotate import AnnotateReporter
  File "/home/shippable/build_ve/python/3.2/lib/python3.2/site-packages/coverage/annotate.py", line 85
    dest.write(u'  ')
                   ^
SyntaxError: invalid syntax
```

**Comment by crempp** [comment]
This appears to be caused by an "issue between coverage and Python 3.2 (py3.2 doesn't accept the
u'' syntax)" [https://github.com/AdamWill/responses/commit/606a05f716ae4b10a6eafedb230e8998cba32ac1]

I've looked around and it seems the accepted solution in most projects is to drop testing of 3.2.

Dropping support for 3.2 automated testing.
