### ISSUE TITLE
Nosetests fail on Shippable in Python 3.4

### ISSUE THREAD

**Issue by crempp** [crempp/mdweb#15]
See https://app.shippable.com/builds/56cc0d3dd583ab0f00fd57f6

```
nosetests --with-coverage --cover-inclusive --cover-package=mdweb --with-xunit --xunit-file=shippable/testresults/nosetests.xml
..SSSSSSS.SSSSS..S...................EEE.EEE
======================================================================
ERROR: test_comments (tests.test_page.TestPageMeta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/tests/test_page.py", line 123, in test_comments
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 42, in __init__
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 65, in _parse_meta_inf
AttributeError: 'module' object has no attribute 'keys'

======================================================================
ERROR: test_metainf_spacing (tests.test_page.TestPageMeta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/tests/test_page.py", line 100, in test_metainf_spacing
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 42, in __init__
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 65, in _parse_meta_inf
AttributeError: 'module' object has no attribute 'keys'

======================================================================
ERROR: test_parse_all_fields (tests.test_page.TestPageMeta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/tests/test_page.py", line 78, in test_parse_all_fields
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 42, in __init__
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 65, in _parse_meta_inf
AttributeError: 'module' object has no attribute 'keys'

======================================================================
ERROR: test_parse_some_fields (tests.test_page.TestPageMeta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/tests/test_page.py", line 58, in test_parse_some_fields
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 42, in __init__
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 65, in _parse_meta_inf
AttributeError: 'module' object has no attribute 'keys'

======================================================================
ERROR: test_unicode (tests.test_page.TestPageMeta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/tests/test_page.py", line 155, in test_unicode
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 42, in __init__
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 65, in _parse_meta_inf
AttributeError: 'module' object has no attribute 'keys'

======================================================================
ERROR: test_unsupported_field (tests.test_page.TestPageMeta)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/tests/test_page.py", line 143, in test_unsupported_field
  File "/opt/pypy-2.2.1-linux64/lib-python/2.7/unittest/case.py", line 471, in assertRaises
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 42, in __init__
  File "/home/shippable/workspace/src/github.com/crempp/mdweb/mdweb/Page.py", line 65, in _parse_meta_inf
AttributeError: 'module' object has no attribute 'keys'

Name                          Stmts   Miss  Cover   Missing
-----------------------------------------------------------
mdweb/Exceptions.py              12      0   100%   
mdweb/Index.py                   13      1    92%   22
mdweb/MDSite.py                  93     17    82%   95, 151-178, 232, 251, 259
mdweb/Navigation.py              78      0   100%   
mdweb/NavigationBaseItem.py       3      0   100%   
mdweb/Page.py                    57      5    91%   60, 63, 67-72
mdweb.py                          0      0   100%   
-----------------------------------------------------------
TOTAL                           256     23    91%   
----------------------------------------------------------------------
Ran 44 tests in 10.375s

FAILED (SKIP=13, errors=6)
```

**Comment by crempp** [comment]
This is not Python 3.4 but rather pypy. I'm removing support for pypy rather than fix this problem at this time.
