### ISSUE TITLE
Support unicode characters in Markdown

### ISSUE THREAD

**Issue by crempp** [crempp/mdweb#46]
On my production server (Python 2.7.6) there appears to be an issue with unicode characters in the markdown.

I can't reproduce this locally yet so it may be difficult to debug.

One potential solution that worked on the server is:

```
import sys

reload(sys)
sys.setdefaultencoding('utf8')
```

```
Traceback (most recent call last):
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/srv/dev.lapinlabs.com/wsgi.py", line 39, in <module>
    app_options={}
  File "/srv/dev.lapinlabs.com/mdweb/MDSite.py", line 107, in __init__
    self.start()
  File "/srv/dev.lapinlabs.com/mdweb/MDSite.py", line 134, in start
    self.navigation = Navigation(self.config['CONTENT_PATH'])
  File "/srv/dev.lapinlabs.com/mdweb/Navigation.py", line 135, in __init__
    self._scan()
  File "/srv/dev.lapinlabs.com/mdweb/Navigation.py", line 221, in _scan
    self.child_navs.append(Navigation(filepath, self.level + 1))
  File "/srv/dev.lapinlabs.com/mdweb/Navigation.py", line 135, in __init__
    self._scan()
  File "/srv/dev.lapinlabs.com/mdweb/Navigation.py", line 206, in _scan
    page = Page(self._root_content_path, filepath)
  File "/srv/dev.lapinlabs.com/mdweb/Page.py", line 73, in __init__
    self.page_html = self.parse_markdown(self.markdown_str)
  File "/srv/dev.lapinlabs.com/mdweb/Page.py", line 84, in parse_markdown
    page_html = markdown.markdown(page_markdown)
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/markdown/__init__.py", line 465, in markdown
    return md.convert(text)
  File "/srv/_virtualenvs/dev.lapinlabs.com/local/lib/python2.7/site-packages/markdown/__init__.py", line 333, in convert
    source = util.text_type(source)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 861: ordinal not in range(128). -- Note: Markdown only accepts unicode input!
```

**Comment by crempp** [comment]
Not sure how to reproduce. Removing from 0.3.

**Comment by crempp** [comment]
After this problem struck again while trying to deploy I decided to dig in.

* It is not happening on my Mac using Python 2.7.10.
* It **is** happening on prod Ubuntu 6.10 using Python 2.7.12
* I found this [issue reported](https://github.com/waylan/Python-Markdown/issues/123) which seems to match the issue I'm experiencing - no help there though
* I found that if I `read().decode('utf8')` in load_page() it solves the problem

I think it's a little heavy handed to assume all .md files are UTF-8 but I'm not excited about the other possible solutions.

**Comment by crempp** [comment]
Possible better solution is `with codecs.open(filename,'r',encoding='utf8') as f:` but that throws an exception in Watchdog, something about threads not shutting down cleanly.

```
Traceback (most recent call last):
   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
   File "/srv/_virtualenvs/chadrempp.com/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 200, in runTraceback (most recent call last):
 <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
   File "/srv/_virtualenvs/chadrempp.com/local/lib/python2.7/site-packages/watchdog/observers/api.py", line 200, in run
 <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'Empty'
```

See https://stackoverflow.com/questions/42250341/python-watchdog-catching-exception
